# Generated by Django 2.2.4 on 2019-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=500)),
                ('solution', models.CharField(max_length=500)),
            ],
        ),
    ]
